# Charlier-based Szasz-type operator
#
# Internal implementation of the Charlier-based positive
# approximation operator.
#
# The Charlier polynomials are generated by
#
#   exp(t) * (1 - t/a)^u
#     = sum_{k=0}^infinity C_k^(a)(u) * t^k / k!,
#
# with a > 1.
#
# For the approximation operator we use
#
#   u = -(a - 1) * n * x,
#
# and
#
#   L_n(f; x, a) =
#     exp(-1) *
#     (1 - 1/a)^((a - 1) * n * x) *
#     sum_{k=0}^infinity
#     C_k^(a)(-(a - 1) * n * x) / k! *
#     f(k/n).
#
# Instead of evaluating Charlier polynomials directly, the
# normalized weights are generated by a stable recurrence.
#
# If
#
#   w_k =
#     exp(-1) *
#     (1 - 1/a)^((a - 1) * n * x) *
#     C_k^(a)(-(a - 1) * n * x) / k!,
#
# then the generating function of the normalized weights is
#
#   W(t) =
#     exp(t - 1) *
#     ((1 - t/a) / (1 - 1/a))^(-(a - 1) * n * x).
#
# From its logarithmic derivative,
#
#   W'(t) / W(t)
#     = 1 + (a - 1) * n * x / (a - t),
#
# one obtains
#
#   a * (k + 1) * w_{k+1}
#     =
#     (a + k + (a - 1) * n * x) * w_k
#     - w_{k-1},
#
# with w_{-1} = 0.


charlier_parameters <- function(operator) {

  parameters <- operator$parameters
  a <- parameters$a

  if (is.null(a) ||
      !is.numeric(a) ||
      length(a) != 1L ||
      !is.finite(a)) {
    stop(
      "`parameters$a` must be supplied as one finite numeric value.",
      call. = FALSE
    )
  }

  if (a <= 1) {
    stop(
      "The Charlier parameter `a` must satisfy `a > 1`.",
      call. = FALSE
    )
  }

  list(
    a = a
  )
}


charlier_control <- function(operator) {

  tol <- operator$control$tol

  if (is.null(tol)) {
    tol <- 1e-12
  }

  if (!is.numeric(tol) ||
      length(tol) != 1L ||
      !is.finite(tol) ||
      tol <= 0 ||
      tol >= 1) {
    stop(
      "`control$tol` must be a number between 0 and 1.",
      call. = FALSE
    )
  }

  max_terms <- operator$control$max_terms

  if (is.null(max_terms)) {
    max_terms <- 100000L
  }

  if (!is.numeric(max_terms) ||
      length(max_terms) != 1L ||
      !is.finite(max_terms) ||
      max_terms < 1 ||
      max_terms != floor(max_terms)) {
    stop(
      "`control$max_terms` must be a positive integer.",
      call. = FALSE
    )
  }

  list(
    tol = tol,
    max_terms = as.integer(max_terms)
  )
}


charlier_initial_weight <- function(x, n, a) {

  log_w0 <-
    -1 +
    (a - 1) * n * x *
    log1p(-1 / a)

  w0 <- exp(log_w0)

  if (!is.finite(w0) || w0 < 0) {
    stop(
      "The initial Charlier weight is invalid.",
      call. = FALSE
    )
  }

  w0
}


charlier_evaluate_one <- function(f, x, operator) {

  if (!is.function(f)) {
    stop(
      "`f` must be a function.",
      call. = FALSE
    )
  }

  if (!is.numeric(x) ||
      length(x) != 1L ||
      !is.finite(x)) {
    stop(
      "`x` must be one finite numeric value.",
      call. = FALSE
    )
  }

  if (x < 0) {
    stop(
      "For the Charlier operator, `x` must be non-negative.",
      call. = FALSE
    )
  }

  n <- operator$n

  pars <- charlier_parameters(operator)
  ctrl <- charlier_control(operator)

  a <- pars$a
  tol <- ctrl$tol
  max_terms <- ctrl$max_terms

  w_prev <- 0
  w_curr <- charlier_initial_weight(
    x = x,
    n = n,
    a = a
  )

  result <- 0
  weight_sum <- 0

  for (k in 0:(max_terms - 1L)) {

    weight <- w_curr

    # Remove negligible negative round-off only.
    if (weight < 0 &&
        abs(weight) <=
        100 * .Machine$double.eps *
        max(1, abs(weight_sum))) {
      weight <- 0
    }

    if (!is.finite(weight) || weight < 0) {
      stop(
        paste0(
          "An invalid Charlier weight was generated at index ",
          k,
          "."
        ),
        call. = FALSE
      )
    }

    node <- k / n

    f_value <- f(node)

    if (!is.numeric(f_value) ||
        length(f_value) != 1L ||
        !is.finite(f_value)) {
      stop(
        "`f` must return one finite numeric value at each Charlier node.",
        call. = FALSE
      )
    }

    result <- result +
      weight * f_value

    weight_sum <- weight_sum +
      weight

    # The normalized Charlier weights must sum to 1.
    if (weight_sum >= 1 - tol &&
        weight_sum <= 1 + tol) {
      return(result)
    }

    if (weight_sum > 1 + 100 * tol) {
      stop(
        paste0(
          "The cumulative Charlier weights exceed 1 ",
          "beyond the allowed numerical tolerance."
        ),
        call. = FALSE
      )
    }

    # Recurrence for the next normalized weight:
    #
    #   a(k+1) w_{k+1}
    #     =
    #     [a + k + (a-1)nx] w_k - w_{k-1}.
    #
    w_next <-
      (
        (
          a +
            k +
            (a - 1) * n * x
        ) * w_curr -
          w_prev
      ) /
      (
        a * (k + 1)
      )

    # Remove negligible negative round-off.
    if (w_next < 0 &&
        abs(w_next) <=
        100 * .Machine$double.eps *
        max(1, abs(w_curr), abs(w_prev))) {
      w_next <- 0
    }

    if (!is.finite(w_next) || w_next < 0) {
      stop(
        paste0(
          "The Charlier weight recurrence produced ",
          "an invalid value at index ",
          k + 1,
          "."
        ),
        call. = FALSE
      )
    }

    w_prev <- w_curr
    w_curr <- w_next
  }

  stop(
    paste0(
      "The Charlier summation did not converge within ",
      max_terms,
      " terms. Increase `control$max_terms` or adjust ",
      "`control$tol`."
    ),
    call. = FALSE
  )
}


charlier_evaluate <- function(f, x, operator) {

  vapply(
    x,
    function(xi) {
      charlier_evaluate_one(
        f = f,
        x = xi,
        operator = operator
      )
    },
    numeric(1)
  )
}
